### ISSUE TITLE
QueryParserError: Invalid content. Lexical error at line 1, column 44.  Encountered: "%" (37), after : ""

### ISSUE THREAD

**Issue by amanjain119** [pbrink231/quickbooks-node-promise#1]
**When I use findAccounts method with the following criteria:-**

```
let criteria = { AccountSubType: 'Inventory' }
let accounts = await qbo.findAccounts(criteria)
```

**I got the following error:-**
```
Error:
   [ { Message: 'Error parsing query',
       Detail:
        'QueryParserError: Invalid content. Lexical error at line 1, column 44.  Encountered: "%" (37), after : ""',
       code: '4000' } ] }
```

**I have fixed this issue by commenting the following code at line number 611 in index.js file:-**

```
query = query.replace(/%/g, '%25')
      .replace(/'/g, '%27')
      .replace(/=/g, '%3D')
      .replace(/</g, '%3C')
      .replace(/>/g, '%3E')
      .replace(/&/g, '%26')
      .replace(/#/g, '%23')
      .replace(/\\/g, '%5C')
      .replace(/\+/g, '%2B')
```

After commenting this code I am able to find accounts with criteria.

Please let me know in case I am doing wrong.

**Comment by pbrink231** [comment]
you were using it correctly.  The new qs package was doing the necessary encoding.  I have removed this additional encoding that was causing a problem on the query.

Update to version 1.1.1 to have the fix working.

**Comment by pbrink231** [comment]
let me know if you see any other criteria issues.
