### ISSUE TITLE
"Operation Cannot consume content type is not supported" when trying to upload

### ISSUE THREAD

**Issue by brianlukoff** [pbrink231/quickbooks-node-promise#24]
I'm trying to upload a file to an invoice but I'm getting "Operation Cannot consume content type is not supported" back from Quickbooks no matter what content type I specify. I'm doing a call like the following -- is this the right invocation of the `upload` method?

```
await qbo.upload('test.pdf', 'application/pdf', fs.createReadStream('test.pdf'), 'Invoice', '1')
```

**Comment by brianlukoff** [comment]
@pbrink231 I've created PR #25 to fix this issue -- would it be possible to merge and release this?

**Comment by pbrink231** [comment]
Going to check it out tomorrow and hopefully get it pushed.

**Comment by brianlukoff** [comment]
Thanks -- much appreciated!

**Comment by pbrink231** [comment]
Pulled in the pull request and made some typescript and error handling updates which are now on 3.3.11
