### ISSUE TITLE
Cannot read property 'Error' of undefined

### ISSUE THREAD

**Issue by pixelpaulaus** [pbrink231/quickbooks-node-promise#3]
i seem to get this error when making api calls....

```
TypeError: Cannot read property 'Error' of undefined
    at response.json.then.json (/home/.../node_modules/quickbooks-node-promise/index.js:488:64)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by pbrink231** [comment]
Can you give me the call you are using.  This is because the returned response is not in json format.  Will clean up the error message at the same time.

**Comment by pixelpaulaus** [comment]
`var qbo = new QuickBooks(this._config, realmID)
    return await qbo.getPreferences().then(userInfo => {
      console.log(userInfo)
      return userInfo
    }).catch(err => {
      console.log(err)
    })`

**Comment by pbrink231** [comment]
I used this code and had no problems when testing.  only changed this._config to QBAppconfig which is where mine was stored.

```
  var qbo = new QuickBooks(QBAppconfig, realmID)
  return await qbo.getPreferences().then(userInfo => {
    console.log(userInfo)
    return userInfo 
  }).catch(err => { 
    console.log(err) 
  })
```

What are you using for your store strategy.  Did you activate your quickbooks successfully?

**Comment by pixelpaulaus** [comment]
the problem is the error handler, it is expecting certain properties. but if the error produced does not have those properties, it throws another error ontop of the original error.
the error handler needs to be not so specific on the original error returned, expecting certain properties.

**Comment by pbrink231** [comment]
This is what I use for testing.  It keeps the credentials in memory so need to re-authorize after restarting your app.  Should change this to use a database.

Yes i first call in a web browser:
localhost:3000/quickbooks/requestToken
This will lead to quickbooks signing in.

Once you are authenticated you will see your token information and can start making calls.

I have all this in the folder example/server.js.  You can run that and it will work.  Just change const `const QuickBooks = require('..')`
to
`const QuickBooks = require('quickbooks-node-promise')`

```
const {
  NODE_ENV,
  QB_APP_KEY,
  QB_APP_SECRET,
  QB_REDIRECT_URL,
  QB_USE_PROD
} = process.env;

// for example only, save to a better location
let realmInfo = {}


class QBStoreStrategy {
  getQBToken({ realmID }) {
    return new Promise((resolve, reject) => {
      console.log('realm info', realmInfo[realmID])
      if (!realmInfo[realmID]) {
        reject("missing realm informaiton")
      } else {
        resolve(realmInfo[realmID])
      }
    })
  }
  storeQBToken(returnedInfo) {
    return new Promise((resolve) => {
      console.log('returned info', returnedInfo)
      realmInfo[returnedInfo.realmID] = {
        realmID: returnedInfo.realmID,
        access_token: returnedInfo.token.access_token,
        refresh_token: returnedInfo.token.refresh_token,
        access_expire_timestamp: returnedInfo.access_expire_timestamp,
        refresh_expire_timestamp: returnedInfo.refresh_expire_timestamp,
        id_token: returnedInfo.id_token
      }
      console.log('saving realm info', realmInfo[returnedInfo.realmID])
      resolve(realmInfo[returnedInfo.realmID])
    })
  }
}


// QB config
QBAppconfig = {
  appKey: QB_APP_KEY,
  appSecret: QB_APP_SECRET,
  redirectUrl: QB_REDIRECT_URL,
  minorversion: 37, /* default is 37, check for your version in the documents */
  useProduction: QB_USE_PROD, /* default is false */
  debug: (NODE_ENV == "production" ? false : true), /* default is false */
  storeStrategy: new QBStoreStrategy(),
  scope: [
    QuickBooks.scopes.Accounting,
    QuickBooks.scopes.OpenId,
    QuickBooks.scopes.Profile,
    QuickBooks.scopes.Email,
    QuickBooks.scopes.Phone,
    QuickBooks.scopes.Address
  ]
}
```

For the error, I agree.  Would like to be able to reproduce your issue and I will fix the error code to be more generalized.

**Comment by pixelpaulaus** [comment]
i got it all working fine. it just the error handler can iitself produce errors which is not good

**Comment by pbrink231** [comment]
Can you let me know how to produce the error you got.  Going to clean up the error and want to have a way to test it.  Wasn’t able to break it.
