### ISSUE TITLE
support for id_token?

### ISSUE THREAD

**Issue by pixelpaulaus** [pbrink231/quickbooks-node-promise#4]
Does this support id_token when doing OpenID Auth?
I have tested it, using only the openid scope.
But it still only returns a access_token,refresh_token and no id_token. Which is done when the user auth via the 'launch' app link and openid is used as the scope.

**Comment by pixelpaulaus** [comment]
just tested with the quickbooks supplied oauth module, and it does return the id_token

**Comment by pbrink231** [comment]
the id_token does come over and is visible in the store and get strategy.  just need to use it.

```
class QBStoreStrategy {
  getQBToken({ realmID }) {
    return new Promise((resolve, reject) => {
      console.log('realm info', realmInfo[realmID])
      if (!realmInfo[realmID]) {
        reject("missing realm informaiton")
      } else {
        resolve(realmInfo[realmID])
      }
    })
  }
  storeQBToken(returnedInfo) {
    return new Promise((resolve) => {
      console.log('returned info', returnedInfo)
      realmInfo[returnedInfo.realmID] = {
        realmID: returnedInfo.realmID,
        access_token: returnedInfo.token.access_token,
        refresh_token: returnedInfo.token.refresh_token,
        access_expire_timestamp: returnedInfo.access_expire_timestamp,
        refresh_expire_timestamp: returnedInfo.refresh_expire_timestamp,
        id_token: returnedInfo.token.id_token
      }
      console.log('saving realm info', realmInfo[returnedInfo.realmID])
      resolve(realmInfo[returnedInfo.realmID])
    })
  }
} 
```

This includes the OpenID token sent back on authorization

**Comment by pixelpaulaus** [comment]
can you provide your code to get the token, and the config?
as i do no get a id_token. even with just openid set as the scope.

**Comment by pbrink231** [comment]
This is my code for testing:
https://github.com/pbrink231/quickbooks-node-promise/blob/master/example/server.js

After starting the server I open a web browser and go to this url:
http://localhost:3000/quickbooks/requestToken
(make sure your port is the one your server is running on)

Follow the prompts.

Do you get an access token and refresh token?

**Comment by pbrink231** [comment]
I updated the saving code.  The id token is in `returnedInfo.token.id_token` and I had in the example i sent before `returnedInfo.id_token` which is now updated to be correct.

This is what is returned to the save storage when I run it with OpenID scope on it.  You can see the id_token inside of the token object with a token sent back.

![image](https://user-images.githubusercontent.com/8224560/65376594-d2f0fc80-dc6f-11e9-89a8-98bb9f5b025e.png)

**Comment by pixelpaulaus** [comment]
got it working thanks
